# Configuration file for Anweddol server
#
# This document contains all of the configurations that the server 
# will be using. Comment or un-comment variables to change their 
# default values. Refer to the units explanations below, 
# and the official anweddol server documentation.

# ---
# Contains all nessessary values for container management.
container:

  # Live OS image path that will be used by containers.
  container_iso_file_path: /etc/anweddol/iso/anweddol_container.iso

  # Max amount of containers domains that can run at the same time.
  # Zero is not allowed, but can be set to 'null' to not
  # provide any restrictions : Make sure your actual system 
  # can support large amount of running container domains before doing so.
  max_allowed_running_container_domains: 6

  # Memory allocated to a container, exprimed in MB.
  container_memory: 1024

  # Numbers of virtual CPUs that are allocated to a container.
  container_vcpus: 2

  # NAT interface name that containers will be using to receive
  # server administration. Default is 'virbr0', which is the default 
  # interface created by the libvirtd daemon when launched.
  nat_interface_name: virbr0

  # The libvirt domain type to specify on container domains XML 
  # description.
  domain_type: kvm

  # The amount of attemps to get network informations of containers
  # before raising an error. If you run Anweddol on a low-performance
  # computer, you may increase this value in order to enable the container
  # domains to start up correctly.
  wait_max_tryout: 20

  # Container endpoint username / password.
  # NOTE : The container endpoint default credentials are public and
  # normalized, that's why they are stored here unencrypted. 
  endpoint_username: endpoint
  endpoint_password: endpoint
  endpoint_listen_port: 22

# ---
# Nessessary parameters for server listen interface.
server:

  # RSA keys paths.
  public_rsa_key_file_path: /etc/anweddol/rsa/public.pem
  private_rsa_key_file_path: /etc/anweddol/rsa/private.pem

  # Server log file path.
  log_file_path: /var/log/anweddol/server.txt

  # PID file path for server daemon process.
  pid_file_path: /etc/anweddol/server_daemon.pid

  # Privilege-separated user with which to run the server.
  # It is not recommended to launch the server with root privileges.
  user: anweddol

  # Server listen informations.
  bind_address: 0.0.0.0
  listen_port: 6150
  timeout: 10

  # Generate RSA key pair on start and use it for the instance.
  # It ignores the stored one, so it may increase startup time.
  enable_onetime_rsa_keys: False

# ---
# Parameters for server web version.
web_server:

  # Web server log file path.
  log_file_path: /var/log/anweddol/web_server.txt

  # PID file path for server daemon process.
  pid_file_path: /etc/anweddol/web_server_daemon.pid

  # Privilege-separated user with which to run web the server.
  # It is not recommended to launch the web server with root privileges.
  user: anweddol

  # Web server listen informations.
  # If 'enable_ssl' below is set to 'True', you may need to change it
  # for 4443 or a similar port for convention matters.
  listen_port: 8080

  # Enable SSL.
  enable_ssl: False

  # SSL private key and certificate file paths.
  ssl_pem_private_key_file_path: /etc/anweddol/ssl/private_key.pem
  ssl_pem_certificate_file_path: /etc/anweddol/ssl/certificate.pem

# ---
# Port forwarding parameters
port_forwarding:

  # The forwardable port range to use.
  # Make sure that the amount of ports specified in the range is
  # at least equal to the 'max_allowed_running_containers' field
  # in the 'container' section, else it will be considered as an error.
  port_range: [10000, 20000]

# ---
# Server log rotation parameters.
log_rotation:

  # Enable this feature or not.
  enabled: True

  # Archived logs folder path.
  log_archive_folder_path: /var/log/anweddol/archived

  # The amount of lines allowed in the file specified in 'log_file_path'
  # in the 'server' section before archiving it.
  max_log_lines_amount: 4000

  # Specify the action on rotation :
  # - 'delete' to delete the actual log file content,
  # - 'archive' to archive log file in a zip format.
  action: archive

# ---
# IP filtering parameters.
ip_filter:

  # Enable this feature or not.
  enabled: False

  # List of allowed / denied IPs.
  # If 'any' is specified in 'denied_ip_list', the server will search in
  # 'allowed_ip_list' for the IP in question. If specified, the server 
  # will accept the connection, and will deny it otherwise.
  denied_ip_list: []

  allowed_ip_list:
    - any

# ---
# Access token parameters.
access_token:

  # Enable this feature or not.
  enabled: False

  # Access token database file path.
  access_token_database_file_path: /etc/anweddol/credentials/access_token.db
